package constants

const HRIS_STATUS_ON_HOLD = 33
const HRIS_STATUS_FAILED = 30
const HRIS_STATUS_PASSED = 31
const HRIS_STATUS_ON_PROGRESS = 32
const HRIS_RUN_TYPE_VALIDATE = 26
const HRIS_RUN_TYPE_FULL = 27
const HRIS_RUN_TYPE_APPEND = 28
