package constants

const HRIS_STATUS_ON_HOLD = 33
const HRIS_STATUS_FAILED = 30
const HRIS_STATUS_PASSED = 31
const HRIS_STATUS_ON_PROGRESS = 32
const HRIS_IMPORT_TYPE_VALIDATE = 26
const HRIS_IMPORT_TYPE_FULL = 27
const HRIS_IMPORT_TYPE_APPEND = 28
const HRIS_FILE_TYPE_EMPLOYEE = 22
const HRIS_FILE_TYPE_ORGANIZATION = 23
